import { LeadStatus, Tag, Role } from './client'

export async function seedDefaultLeadStatuses(
  workspaceId: string,
  userId: string
) {
  const defaultStatuses = [
    {
      workspaceId,
      name: 'New',
      color: '#3b82f6',
      description: 'Newly created leads',
      order: 1,
      isDefault: true,
      isActive: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Contacted',
      color: '#f59e0b',
      description: 'Initial contact made',
      order: 2,
      isDefault: false,
      isActive: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Qualified',
      color: '#10b981',
      description: 'Lead has been qualified',
      order: 3,
      isDefault: false,
      isActive: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Proposal',
      color: '#8b5cf6',
      description: 'Proposal sent',
      order: 4,
      isDefault: false,
      isActive: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Negotiation',
      color: '#f97316',
      description: 'In negotiation phase',
      order: 5,
      isDefault: false,
      isActive: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Closed Won',
      color: '#22c55e',
      description: 'Successfully closed',
      order: 6,
      isDefault: false,
      isActive: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Closed Lost',
      color: '#ef4444',
      description: 'Lost opportunity',
      order: 7,
      isDefault: false,
      isActive: true,
      createdBy: userId,
    },
  ]

  try {
    const existingCount = await LeadStatus.countDocuments({ workspaceId })
    if (existingCount === 0) {
      await LeadStatus.insertMany(defaultStatuses)
    }
  } catch (error) {}
}

export async function seedDefaultTags(workspaceId: string, userId: string) {
  const defaultTags = [
    {
      workspaceId,
      name: 'Hot Lead',
      color: '#ef4444',
      description: 'High priority leads',
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Warm Lead',
      color: '#f59e0b',
      description: 'Medium priority leads',
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Cold Lead',
      color: '#6b7280',
      description: 'Low priority leads',
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Enterprise',
      color: '#8b5cf6',
      description: 'Enterprise clients',
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'SMB',
      color: '#10b981',
      description: 'Small and medium business',
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Follow Up',
      color: '#3b82f6',
      description: 'Requires follow up',
      createdBy: userId,
    },
  ]

  try {
    const existingCount = await Tag.countDocuments({ workspaceId })
    if (existingCount === 0) {
      await Tag.insertMany(defaultTags)
    }
  } catch (error) {}
}

export async function seedDefaultRoles(workspaceId: string, userId: string) {
  const defaultRoles = [
    {
      workspaceId,
      name: 'Owner',
      description: 'Full system access and workspace ownership',
      permissions: ['*:*'],
      isDefault: true,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Admin',
      description:
        'Administrative access — everything except workspace deletion and billing',
      permissions: [
        'workspace.view',
        'workspace.edit',
        'workspace.invite',
        'activities.view',
        'notifications.view',
        'notifications.manage',
        'settings.view',
        'settings.edit',
        'leads.view',
        'leads.create',
        'leads.edit',
        'leads.delete',
        'leads.assign',
        'leads.export',
        'leads.convert',
        'contacts.view',
        'contacts.create',
        'contacts.edit',
        'contacts.delete',
        'contacts.export',
        'lead_notes.view',
        'lead_notes.create',
        'lead_notes.edit',
        'lead_notes.delete',
        'lead_activities.view',
        'lead_statuses.view',
        'lead_statuses.create',
        'lead_statuses.edit',
        'lead_statuses.delete',
        'tags.view',
        'tags.create',
        'tags.edit',
        'tags.delete',
        'users.view',
        'users.create',
        'users.edit',
        'members.view',
        'members.invite',
        'members.edit',
        'members.remove',
        'roles.view',
        'roles.create',
        'roles.edit',
        'roles.delete',
        'permissions.view',
        'invitations.view',
        'invitations.create',
        'invitations.cancel',
        'chat.view',
        'chat.send',
        'chat.create_room',
        'chat.manage_room',
        'chat.delete_messages',
        'chat.upload_files',
        'chat.moderate',
        'analytics.view',
        'reports.view',
        'reports.export',
        'webhooks.view',
        'webhooks.create',
        'webhooks.edit',
        'webhooks.delete',
        'projects.view',
        'projects.create',
        'projects.edit',
        'projects.delete',
        'projects.manage',
        'project_members.view',
        'project_members.invite',
        'project_members.edit',
        'project_members.remove',
        'project_members.manage',
        'tasks.view',
        'tasks.create',
        'tasks.edit',
        'tasks.delete',
        'tasks.assign',
        'tasks.manage',
        'documents.view',
        'documents.create',
        'documents.edit',
        'documents.delete',
        'documents.share',
        'documents.manage',
        'columns.view',
        'columns.create',
        'columns.edit',
        'columns.delete',
      ],
      isDefault: false,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Sales Manager',
      description: 'Manage sales team, leads, contacts, and view reports',
      permissions: [
        'workspace.view',
        'activities.view',
        'notifications.view',
        'settings.view',
        'leads.view',
        'leads.create',
        'leads.edit',
        'leads.delete',
        'leads.assign',
        'leads.export',
        'leads.convert',
        'contacts.view',
        'contacts.create',
        'contacts.edit',
        'contacts.delete',
        'contacts.export',
        'lead_notes.view',
        'lead_notes.create',
        'lead_notes.edit',
        'lead_notes.delete',
        'lead_activities.view',
        'lead_statuses.view',
        'tags.view',
        'tags.create',
        'tags.edit',
        'users.view',
        'members.view',
        'chat.view',
        'chat.send',
        'chat.create_room',
        'chat.manage_room',
        'chat.upload_files',
        'analytics.view',
        'reports.view',
        'reports.export',
        'webhooks.view',
        'projects.view',
        'projects.create',
        'projects.edit',
        'project_members.view',
        'project_members.invite',
        'tasks.view',
        'tasks.create',
        'tasks.edit',
        'tasks.assign',
        'documents.view',
        'documents.create',
        'documents.edit',
        'columns.view',
      ],
      isDefault: false,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Sales Rep',
      description: 'Create and manage own leads, contacts, and tasks',
      permissions: [
        'workspace.view',
        'activities.view',
        'notifications.view',
        'settings.view',
        'leads.view',
        'leads.create',
        'leads.edit',
        'contacts.view',
        'contacts.create',
        'contacts.edit',
        'lead_notes.view',
        'lead_notes.create',
        'lead_notes.edit',
        'lead_activities.view',
        'lead_statuses.view',
        'tags.view',
        'members.view',
        'chat.view',
        'chat.send',
        'chat.upload_files',
        'analytics.view',
        'projects.view',
        'project_members.view',
        'tasks.view',
        'tasks.create',
        'tasks.edit',
        'documents.view',
        'documents.create',
        'columns.view',
      ],
      isDefault: false,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Project Manager',
      description:
        'Full project management — tasks, docs, members, and sprints',
      permissions: [
        'workspace.view',
        'activities.view',
        'notifications.view',
        'settings.view',
        'members.view',
        'chat.view',
        'chat.send',
        'chat.create_room',
        'chat.upload_files',
        'projects.view',
        'projects.create',
        'projects.edit',
        'projects.manage',
        'project_members.view',
        'project_members.invite',
        'project_members.edit',
        'project_members.remove',
        'project_members.manage',
        'tasks.view',
        'tasks.create',
        'tasks.edit',
        'tasks.delete',
        'tasks.assign',
        'tasks.manage',
        'documents.view',
        'documents.create',
        'documents.edit',
        'documents.delete',
        'documents.share',
        'documents.manage',
        'columns.view',
        'columns.create',
        'columns.edit',
        'columns.delete',
        'analytics.view',
        'reports.view',
      ],
      isDefault: false,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'HR Manager',
      description: 'Manage employees, attendance, leaves, and assets',
      permissions: [
        'workspace.view',
        'activities.view',
        'notifications.view',
        'settings.view',
        'users.view',
        'members.view',
        'members.invite',
        'members.edit',
        'chat.view',
        'chat.send',
        'chat.upload_files',
        'analytics.view',
        'reports.view',
        'reports.export',
      ],
      isDefault: false,
      createdBy: userId,
    },
    {
      workspaceId,
      name: 'Viewer',
      description: 'Read-only access — can view but not modify anything',
      permissions: [
        'workspace.view',
        'activities.view',
        'notifications.view',
        'settings.view',
        'leads.view',
        'contacts.view',
        'lead_notes.view',
        'lead_activities.view',
        'lead_statuses.view',
        'tags.view',
        'members.view',
        'chat.view',
        'analytics.view',
        'reports.view',
        'projects.view',
        'project_members.view',
        'tasks.view',
        'documents.view',
        'columns.view',
      ],
      isDefault: false,
      createdBy: userId,
    },
  ]

  try {
    const existingCount = await Role.countDocuments({ workspaceId })
    if (existingCount === 0) {
      await Role.insertMany(defaultRoles)
    }
  } catch (error) {}
}

export async function seedWorkspaceDefaults(
  workspaceId: string,
  userId: string
) {
  await Promise.all([
    seedDefaultLeadStatuses(workspaceId, userId),
    seedDefaultTags(workspaceId, userId),
    seedDefaultRoles(workspaceId, userId),
  ])
}
