apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-app
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "200"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  rules:
    - host: crm.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-crm-app
                port:
                  name: http
  tls:
    - hosts:
        - crm.example.com
      secretName: crm-tls-prod
