const mongoose = require('mongoose')

const MONGODB_URI =
  process.env.MONGODB_URI ||
  'mongodb+srv://shivaysharmachemistry_db_user:OvLa48iycJGuvtlZ@crm.nh3cind.mongodb.net/crm-sass?retryWrites=true&w=majority'

const roles = [
  {
    name: 'Owner',
    description: 'Full system access and workspace ownership',
    permissions: ['*:*'],
    isDefault: true,
  },
  {
    name: 'Admin',
    description:
      'Administrative access — everything except workspace deletion and billing',
    permissions: [
      'workspace.view',
      'workspace.edit',
      'workspace.invite',
      'activities.view',
      'notifications.view',
      'notifications.manage',
      'settings.view',
      'settings.edit',
      'leads.view',
      'leads.create',
      'leads.edit',
      'leads.delete',
      'leads.assign',
      'leads.export',
      'leads.convert',
      'contacts.view',
      'contacts.create',
      'contacts.edit',
      'contacts.delete',
      'contacts.export',
      'lead_notes.view',
      'lead_notes.create',
      'lead_notes.edit',
      'lead_notes.delete',
      'lead_activities.view',
      'lead_statuses.view',
      'lead_statuses.create',
      'lead_statuses.edit',
      'lead_statuses.delete',
      'tags.view',
      'tags.create',
      'tags.edit',
      'tags.delete',
      'users.view',
      'users.create',
      'users.edit',
      'members.view',
      'members.invite',
      'members.edit',
      'members.remove',
      'roles.view',
      'roles.create',
      'roles.edit',
      'roles.delete',
      'permissions.view',
      'invitations.view',
      'invitations.create',
      'invitations.cancel',
      'chat.view',
      'chat.send',
      'chat.create_room',
      'chat.manage_room',
      'chat.delete_messages',
      'chat.upload_files',
      'chat.moderate',
      'analytics.view',
      'reports.view',
      'reports.export',
      'webhooks.view',
      'webhooks.create',
      'webhooks.edit',
      'webhooks.delete',
      'projects.view',
      'projects.create',
      'projects.edit',
      'projects.delete',
      'projects.manage',
      'project_members.view',
      'project_members.invite',
      'project_members.edit',
      'project_members.remove',
      'project_members.manage',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'tasks.assign',
      'tasks.manage',
      'documents.view',
      'documents.create',
      'documents.edit',
      'documents.delete',
      'documents.share',
      'documents.manage',
      'columns.view',
      'columns.create',
      'columns.edit',
      'columns.delete',
    ],
    isDefault: false,
  },
  {
    name: 'Sales Manager',
    description: 'Manage sales team, leads, contacts, and view reports',
    permissions: [
      'workspace.view',
      'activities.view',
      'notifications.view',
      'settings.view',
      'leads.view',
      'leads.create',
      'leads.edit',
      'leads.delete',
      'leads.assign',
      'leads.export',
      'leads.convert',
      'contacts.view',
      'contacts.create',
      'contacts.edit',
      'contacts.delete',
      'contacts.export',
      'lead_notes.view',
      'lead_notes.create',
      'lead_notes.edit',
      'lead_notes.delete',
      'lead_activities.view',
      'lead_statuses.view',
      'tags.view',
      'tags.create',
      'tags.edit',
      'users.view',
      'members.view',
      'chat.view',
      'chat.send',
      'chat.create_room',
      'chat.manage_room',
      'chat.upload_files',
      'analytics.view',
      'reports.view',
      'reports.export',
      'webhooks.view',
      'projects.view',
      'projects.create',
      'projects.edit',
      'project_members.view',
      'project_members.invite',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.assign',
      'documents.view',
      'documents.create',
      'documents.edit',
      'columns.view',
    ],
    isDefault: false,
  },
  {
    name: 'Sales Rep',
    description: 'Create and manage own leads, contacts, and tasks',
    permissions: [
      'workspace.view',
      'activities.view',
      'notifications.view',
      'settings.view',
      'leads.view',
      'leads.create',
      'leads.edit',
      'contacts.view',
      'contacts.create',
      'contacts.edit',
      'lead_notes.view',
      'lead_notes.create',
      'lead_notes.edit',
      'lead_activities.view',
      'lead_statuses.view',
      'tags.view',
      'members.view',
      'chat.view',
      'chat.send',
      'chat.upload_files',
      'analytics.view',
      'projects.view',
      'project_members.view',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'documents.view',
      'documents.create',
      'columns.view',
    ],
    isDefault: false,
  },
  {
    name: 'Project Manager',
    description: 'Full project management — tasks, docs, members, and sprints',
    permissions: [
      'workspace.view',
      'activities.view',
      'notifications.view',
      'settings.view',
      'members.view',
      'chat.view',
      'chat.send',
      'chat.create_room',
      'chat.upload_files',
      'projects.view',
      'projects.create',
      'projects.edit',
      'projects.manage',
      'project_members.view',
      'project_members.invite',
      'project_members.edit',
      'project_members.remove',
      'project_members.manage',
      'tasks.view',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'tasks.assign',
      'tasks.manage',
      'documents.view',
      'documents.create',
      'documents.edit',
      'documents.delete',
      'documents.share',
      'documents.manage',
      'columns.view',
      'columns.create',
      'columns.edit',
      'columns.delete',
      'analytics.view',
      'reports.view',
    ],
    isDefault: false,
  },
  {
    name: 'HR Manager',
    description: 'Manage employees, attendance, leaves, and assets',
    permissions: [
      'workspace.view',
      'activities.view',
      'notifications.view',
      'settings.view',
      'users.view',
      'members.view',
      'members.invite',
      'members.edit',
      'chat.view',
      'chat.send',
      'chat.upload_files',
      'analytics.view',
      'reports.view',
      'reports.export',
    ],
    isDefault: false,
  },
  {
    name: 'Viewer',
    description: 'Read-only access — can view but not modify anything',
    permissions: [
      'workspace.view',
      'activities.view',
      'notifications.view',
      'settings.view',
      'leads.view',
      'contacts.view',
      'lead_notes.view',
      'lead_activities.view',
      'lead_statuses.view',
      'tags.view',
      'members.view',
      'chat.view',
      'analytics.view',
      'reports.view',
      'projects.view',
      'project_members.view',
      'tasks.view',
      'documents.view',
      'columns.view',
    ],
    isDefault: false,
  },
]

async function seed() {
  await mongoose.connect(MONGODB_URI)
  console.log('Connected to MongoDB')

  const db = mongoose.connection.db
  const existing = await db.collection('roles').countDocuments()
  console.log('Existing roles:', existing)

  if (existing > 0) {
    await db.collection('roles').deleteMany({})
    console.log('Cleared existing roles')
  }

  const now = new Date()
  const docs = roles.map(r => ({
    ...r,
    workspaceId: 'default',
    createdBy: 'system-seed',
    createdAt: now,
    updatedAt: now,
  }))

  await db.collection('roles').insertMany(docs)
  console.log(
    'Seeded ' + docs.length + ' roles: ' + docs.map(r => r.name).join(', ')
  )

  await mongoose.disconnect()
  console.log('Done')
}

seed().catch(e => {
  console.error('ERROR:', e.message)
  process.exit(1)
})
